# The script of the game goes in this file.

# Cited URL: https://pmc.ncbi.nlm.nih.gov/articles/PMC10971579/
#TODO: https://pmc.ncbi.nlm.nih.gov/articles/PMC8470184/ (NEW!!!)

# Declare characters used by this game. The color argument colorizes the
# name of the character.

define n = Character("")
define p = Character("")
# The game starts here.

transform proper_fit:
    # Fit image to screen while maintaining aspect ratio
    size (1920, 1080) # Standard HD resolution
    fit "contain"   # Ensures whole image is visible

transform data_focus:
    # For graphs and charts
    size (1920, 1080) 
    zoom 1.2

transform general_focus:
    size(1920, 1080)
    zoom 1.01


label start:

    scene bg room

    "Do you want to see my thesis first?"

menu ifSeeThesis:

    "yes":
        jump thesis

    "No, I need to go through the whole thing":
        jump intro

label intro:

    scene bg room at proper_fit

    p "HI my dear partner! "

    p "You always tell me that our campus has the state-of-art\ basic infrastructure in China..."

    p "...And you are right!"

    p "But to be the best doesn't mean that there is nothing to be improved."

    p "We've lived in this campus for months, yet we tend to\ ignore some obvious problems right around us."

    p "Actually at this moment, there is a part of this campus\ needs an urgent improvement."

    p "..."

    p "Let me show you what is happening right now around us\ in an obvious corner..."

    p "...yet an invisible one."

    scene uncleaned corridor at proper_fit

    p "This is the public space of our residential college.\ As you can see, there are..."

    p "...lots of large cardboard paper boxes around the dustbin."

    p "However, it's not the paper boxes that causes any problem,\ but the trash in them."

    p "You see, students tend to dump their trash into the paper boxes\ rather than the dustbin besides them..."

    p "...which is problematic since there is considerable amount of\ organic waste, which tends to..."

    p "...produces terrible smell before they get cleaned."

    "I knew that you are happier if everything is tidy and clean, and you are keen on environment protection."

    "So surely you will want to take action to get rid of this problem."

    "Given that you have rich experience negotiating with others and managed to persuade\ the students' union into doing something beneficial in high school,"

    p "I suggest that we should have a face-to-face discussion with\ Students' union of our College and persuade them into setting up a recycling spots in the RC..."

    p "...just like the one in the postal service center, in which large carpel\ boxes can be gathered, compressed and recycled."

    "So that no more empty carpel boxes will lie around the public area of our college,\ containing organic waste that gives off nasty smells,..."

    "...which will certainly make our RC a better place to live in."

    n "But..."

menu ifserious:

    n "...Can some terrible smell possibly do any serious harm?"

    "Of course! It's worrying,":
        
        $ serious = True
        jump seriousTrue   
    
    "That's nasty, but seems harmless":

        $ serious = False
        jump seriousFalse
        

label seriousFalse:

    scene cover paper at proper_fit with fade

    p "You may argue that such smells is just nasty, not really harmful."

    p "Let's go through this article together and you may change your mind..."

    jump readArticle

label seriousTrue:

    scene cover paper at proper_fit with fade

    p "You are absolutely right! Insignificant as it might seems\ at your first glance..."

    p "The negative influence caused by the smell\ generated by organic waste can't be possibly ignored."

    p "Would you like me to elaborate on this topic further?"

menu ifreadArticle:

    "Do you need to go through this article about the potential harm\ of nasty smells generated by organic waste?"

    "Yes":
        $ ifRead = True
        jump readArticle

    "No, thanks":
        $ idRead = False
        pass

label readArticle:

    scene data paper at data_focus with fade

    "You know how our corridor sometimes smells like fermented food, especially on weekends?"

    "These smells are what we called organic emissions"

    "That smell isn't just unpleasant. "

    p "This picture is cited from research published on Environmental Technology &amp; Innovation."

    "It focuses on the emission produced by house-hold organic waste and their harms,..."

    "...and I think it can help us figure out what is going on in our hallway since the situation is basically the same:"

    "The research focuses on the organic waste emissions in enclosed space ('house-hold')..."
    
    "...and our hallway can also be considered as an enclosed space with organic waste emission."

    "According to the research, when food and organic waste, just like these ones in the carpel boxes, breaks down,..." 

    "...it releases various kinds of chemicals into the air."

    "The most common chemical released is ethanol (alcohol)."

    scene figure4 article at data_focus with fade

    "Harmless as it might be at your first glance, there is strong relationship..."

    "...between daily exposure to alcohol and increased possibility of getting cancer."

    "This picture describes the risk for cancer at different sites..."

    "...for a person exposing himself in alcohol every day."

    scene abstract paper at proper_fit with fade

    p "According to an article on this issue by\ Paulina,Rudziak, Evans Batung and Isaac Luginaah published PLOS ONE,..."

    p "...they examined data from 32 different communities\ across 12 countries, and found that..."

    "...people have reported that emissions from organic waste makes their eyes itch."

    "Think about it: we have dozens of students in one RC unit wing alone..."

    "...Each person throws away food waste almost daily, and those boxes sit there for days!"

    "So it's likely that these odors will always be around."

    "Which means that after living in the RC and being around these smells for a while,..."

    "...our nose tends to adapt to the smell and 'forget' about it, leaving our body still being affected!"

    "Last but not the least, being around these smell for a long time can increase our stress level,..."

    "This is definitely not something we want to see happening on students dealing with approaching deadlines."

label possibleSolution:

    scene uncleaned corridor at proper_fit with fade

    p "As a conclusion, these odors does no good to the residents of our college."

    p "So we may agree that immediate action should be taken."

    p "Previously I proposed a recycle based solution, any other ideas?"

menu chooseSolution:

    "How to deal with this piece of mess?"

    "Why not tell everyone that they shouldn't place their cardboard paper boxes randomly?":

        $ choose = 0
        jump solution0

    "We should use larger dustbins so that the cardboard paper boxes can be thrown into them!":

        $ choose = 1
        jump solution1

    "I agree that we should set up some recycling points in the residential college\ so that no more cardboard paper boxes will end up being placed around the dustbin?":

        $ choose = 2
        jump solution2  

label solution0:

    scene clean dustbin at proper_fit with fade

    p "This is a 'simple' solution..."

    p "...yet an impractical one. The reasons are as follow:"

    p "Where does these cardboard paper boxes come from? Postal services clearly."

    p "We all know that there is a recycling spot in the postal service spot of our campus..."

    p "...So why would anyone be bothered to take the boxes\ back to the dormitory instead of just putting them at the recycling spot?"

    p "Because the content inside the package is\ too large or heavy to be carried by bare hand..."

    p "...which means that A.Sometimes students have to take back large paper boxes,\ B.They have to throw them somewhere."

    p "Even if they choose not to throw then in the college..."

    p "...these paper boxes will eventually end up somewhere\ out of the residential college but still in this campus."

    p "You see? This solution transfers the problem to somewhere outside the residential college..."

    p "...but doesn't solve it."

    jump chooseSolution

    
label solution1:

    scene big dustbin at proper_fit with fade

    p "This one sound better than the previous solution..."

    p "...but is not good enough as well. The reasons are as follow:"

    "First, this won't solve the organic emission issue."

    p "Assuming that you have successfully persuade\ the students' union of the residential college into..."

    p "...replace present dustbins with larger one.\ what will happen next?"

    p "At first, students will put their paper boxes\ into the dustbin, which is good..."

    p "But we should keep in mind that the population\ of our college is growing as time goes by."

    p "More students will take in more paper boxes, large dustbins are needed to contain these boxes..."

    "Someday the dustbin can't contain more trash, and some carpel boxes will still..."

    "...end up around the dustbin, not in them."

    p "You see? This is a dead end. We can't solve more with more; we need to solve more with less."

    p "with that in mind, let's choose again and see if there is a better solution."

    jump chooseSolution

label solution2:
# TODO: a picture of recycle spot in the postal service center

    scene recycle spot at general_focus

    p "Now we are speaking the same language!"

    "Right now there are only one recycle spot in the campus,\ which is the one in the postal service center."

    "We can't expect everyone to bring their trash to the spot,\ so we bring the spot ot them."

# TODO: a picture of empty discussion room here

    scene empty discussionroom at proper_fit

    "To be more specific, you can see that some of the discussion rooms of our RC are always available..."

    "...maybe it's possible for us to turn it into a recycle spot, just like the one in the postal service center."

    "We can 'hire' some volunteers within the RC or from the eco club and ask them to flatten the boxes on a regular basis."

    p "To put this solution into action takes much efforts, time and money..."

    p "But it's worthwhile! Let me further explain\ the advantages of this solution over other ones to you."

    "First, no more organic emissions will be generated\ since there will be no chance to throw organic waste in the carpel boxes!" 

    p "Plus, If you have already went through the first solution,\ you will know that students takes back large cardboard boxes..."

    p "...because content inside the package is too large or heavy\ to be carried by bare hand..."

    p "...and they put it besides the dustbin because they can't throw it elsewhere."

    p "By setting up recycling spots in the residential college,\ not only it will provides students with a place to throw there boxes..."

    p "...but also it will not be overwhelmed (like the enlarged dustbins in solution 2)\ since the cardboard paper boxes can be easily compressed..."

    p "...and sold to recycling stations outside the campus."

    p "You see? That's how we will solve the problem"

    jump thesis

label thesis:
    #TODO: replace the picture here.

    scene sd un at proper_fit with fade

    p "OK here we are."

    p "I know that an environment-protection fascinated student like you..."

    p "...will do something to solve this problem."

    p "By doing so, not only will we get a residential college free from nasty smell..."

    p "...but also we can inspire others to take action to find and\ solve more invisible problems like this one."

    p "We should now have a face-to-face discussion with Students' union of our RC..."

    p "...to persuade them into setting up more recycling points..."

    p "...in which students' large carpel boxes are gathered, compressed and recycled,..."

    p "...so that there won't be more nasty smells produced by overwhelmed dustbin in the college"

    n "But why would the students' union even care about this problem? Is there any exigency?"

    p "Of course. First, if they choose to ignore the problem, not only will the residents of our college..."

    p "...but also will damage their image among the students."

    p "On the other hand, if they choose to solve this problem, they\ will manage to do something and gain a good reputation!"

label citation:

    scene end

    "1.	Rudziak , Paulina, et al.“The effects of gases from food waste on human health: "

    "A systematic review”, PLOS One, 2024 May. 27;"

    "https://doi.org/10.1371/journal.pone.0300801 Accessed 5 Nov.2024"

    "2.	Cui, Yuxue, et al. “The emission of volatile organic compounds during the initial decompositio..." 
    
    "...stage of food waste and its relationship with the bacterial community.”, ..."

    "...Environmental Technology &amp; Innovation, vol. 27, 2022 Mar.11; "
    
    "https://doi.org/10.1016/j.eti.2022.102443 Accessed 5 Nov.2024"

    "3. Rumgay, Harriet, et al. “Alcohol and Cancer:Epidemiology and biological"

    "Mechanisms”, Nutrients, 2021 Sep 11; 13(9):3173; "

    "https://doi.org/10.3390/nu13093173 Accessed 18 Nov.2024"

    "4. Ahmed, Farid E. “Toxicological Effects of Ethanol on Human Health."

    "Critical Reviews in Toxicology 25 (4): 347–67. 25 Sep 2008;"

    "https://doi:10.3109/10408449509021614."



    return
