# The script of the game goes in this file.

# Cited URL: https://pmc.ncbi.nlm.nih.gov/articles/PMC10971579/

# Declare characters used by this game. The color argument colorizes the
# name of the character.

define n = Character("Nie")
define p = Character("Patrick")
# The game starts here.

label start:

    scene bg room

    "Do you want to see my thesis & exigency first?"


menu ifSeeThesis:

    "yes":
        jump thesis

    "No, I need to go through the whole thing":
        jump intro


label intro:

    scene intro room

    p "HI my dear partner! "

    p "You always tell me that our campus has the state-of-art\ basic infrastructure in China..."

    p "...And you are right!"

    p "But to be the best doesn't mean that there are nothing to be improved."

    p "We've lived in this campus for months, yet we tend to\ ignore some obvious problems right around us."

    p "Actually at this moment, there is a part of this campus\ needs an urgent improvement."

    p "..."

    p "Let me show you what is happening right now around us\ in an obvious corner..."

    p "...yet an invisible one."

    scene uncleaned corridor

    p "This is the public space of our residential college.\ As you can see, there are..."

    p "...lots of large cardboard paper boxes around the dustbin."

    p "However, it's not the paper boxes that causes any problem,\ but the trash in them."

    p "You see, students tend to dump their trash into the paper boxes\ rather than the dustbin besides them..."

    p "...which is problematic since there is considerable amount of\ organic waste, which tends to..."

    p "...produces terrible smell before they get cleaned."

    p "Now, do you think this will be a serious problem?"


menu ifserious:

    "Can some terrible smell possibly do any serious harm?"

    "Of course! It's worrying,":
        
        $ serious = True
        jump seriousTrue   
    
    "That's nasty, but seems harmless":

        $ serious = False
        jump seriousFalse
        

label seriousFalse:

    scene abstract paper

    p "You may argue that such smells is just nasty, not really harmful."

    p "Let's go through this article together and you may change your mind..."

    jump readArticle


label seriousTrue:

    scene abstract paper

    p "You are absolutely right! Insignificant as it might seems\ at your first glance..."

    p "The negative influence caused by the smell\ generated by organic waste can't be possibly ignored."

    p "Would you like me to elaborate on this topic further?"


menu ifreadArticle:

    "Do you need to go through this article about the potential harm\ of nasty smells generated by organic waste?"

    "Yes":
        $ ifRead = True
        jump readArticle

    "No, thanks":
        $ idRead = False
        pass


label readArticle:

    scene data paper

    p "This picture is cited from another research published on Environmental Technology &amp; Innovation,..."

    p "...according to which there is considerable amount of alcohols, esters, aldehydes-ketones in the..." 

    p "...emissions of organic waste. And 'ethanol was the primary\ compound with the maximum concentration of 825 mg/N per m3'"

    p "The ethanol was particularly worrying because according to a research published on Critical Reviews in Toxicology,..."

    p "...'Ethanol can lead to malnutritionand can exert a direct toxicological effect\ due to its interference with hepatic..."

    p "...metabolism and immunological functions.'(Ahmed, Farid E,1995)"

    scene abstract paper

    p "According to an article on this issue by\ Paulina,Rudziak, Evans Batung and Isaac Luginaah published PLOS ONE,..."

    p "...they examined data from 32 different communities\ across 12 countries, and found that..."

    p "...'The evidence provided here shows a positive linkage\ between food waste emissions and both direct and indirect human health impacts.'"

    p "This article also mentioned that\ 'the emissions of food waste, such as ammonia gas, ..."

    p "...have social health costs in addition to environmental health and human physiological health'"

    p "And from a psychological point of view,\ many have reported that to expose to these emissions..."

    p "...causes eye irritation and sensory adaptation issues."

    p "Last but not the least, from a long-term point of view,\ thses odors elevated stress hormones..."

    p "...in long-term exposed individuals,\ which is the least thing we want to see..."

    p "...on a stressful university student with tight time scheduals"


label possibleSolution:

    scene uncleaned corridor

    p "As a conclusion, these odours does no good to the residents of our college."

    p "So we may agree that immeadiate action should be taken."

    p "Here are some possible solutions, but are they practical or even make sense after all?"


menu chooseSolution:

    "How to deal with this piece of mess?"

    "Why not tell everyone that they should't place their cardboard paper boxes ramdonly?":

        $ choose = 0
        jump solution0

    "We should use larger dustbins so that the cardboard paper boxes can be thrown into them!":

        $ choose = 1
        jump solution1

    "Why not set up some recycling points in the residential college\ so that no more cardboard paper boxes will end up being placed around the dustbin?":

        $ choose = 2
        jump solution2  


label solution0:

    scene clean dustbin

    p "This is a 'simple' solution..."

    p "...yet an impractical one. The reasons are as follow:"

    p "Where does these cardboard paper boxes come from? Postal services clearly."

    p "We all know that there is a recycling spot in the postal service spot of our campus..."

    p "...So why would anyone be bothered to take the boxes\ back to the domitory instead of just putting them at the recycling spot?"

    p "Because the content inside the package is\ too large or heavy to be carried by bare hand..."

    p "...which means that A.Sometimes students have to take back large paper boxes,\ B.They have to throw them somewhere."

    p "Even if they choose not to throw then in the college..."

    p "...these paper boxes will eventually end up somewher\ out of the residential college but still in this campus."

    p "You see? This solution transfers the problem to somewhere outside the residential college..."

    p "...but doesn't solve it."

    jump chooseSolution

    
label solution1:

    scene big dustbin

    p "This one sounds better than the previous solution..."

    p "...but is not good enough as well. The reasons are as follow:"

    p "Assuming that you have successfully persuade\ the students'union of the residential college into..."

    p "...replace present dustbins with larger one.\ what will happen next?"

    p "At first, students will put their paper boxes\ into the dustbin, which is good..."

    p "But we should keep in mind that the population\ of our college is growing as time goes by."

    p "More students wtll take in more paper boxes, large dustbins are needed to contain these boxes..."

    p "You see? This is a dead end. We can't solve more with more, we need to solve more with less."

    p "with that in mind, let's choose again and see if there is a betters solution."

    jump chooseSolution


label solution2:
# TODO: a picture of recycle spot in the postal service center

    scene recycle spot

    p "From my point of view, this is the best solution!"

    p "To put this solution into action takes much efforts, time and money..."

    p "But it's worhtwhile! Let me further explain\ the advantages of this solution over other ones to you."

    p "If you have already went through the first solution,\ you will know that students takes back large carpboard..."

    p "...because content inside the package is too large or heavy\ to be carried by bare hand..."

    p "...and they put it besides the dustbin because they can't throw it elsewhere."

    p "By setting up recycling spots in the residential college,\ not only it will provides students with a place to throw there boxes..."

    p "...but also it will not be overwhelmed (like the enlarged dustbins in solution 2)\ since the caedboard paper boxes can be easily compressed..."

    p "...and sold to recycling stations outside the campus."

    p "You see? That's how we will solve the problem"

    jump thesis


label thesis:
    #TODO: a picture of RC-101 here.

    scene sd un

    p "OK here we are."

    p "I know that an environment-protection fanscinated student like you..."

    p "...will do something to solve this problem."

    p "By doing so, not only will we get a residential college free from nasty smell..."

    p "...but also we can inspire others to take action to find and\ solve more invisible problems like this one."

    p "We should now have a face to face discussion with Students' union of our College..."

    p "...to persuade them into setting up more recycling points..."

    p "...in which students' large carpel boxes are gathered, compressed and recycled,..."

    p "...so that there won't be more nasty smells produced by overwhelmed dustbin in the college"

    n "But why would the students' union even care about this problem? Is there any exigency?"

    p "Of course. First, if they choose to ignore the problem, not only will the residents of our college..."

    p "...but also will damage their image among the students."

    p "On the other hand, if they choose to solve this problem, they\ will manage to do something and gain a good reputation!"

    return
